export const validLocations = [
  { value: "abia", label: "Abia" },
  { value: "adamawa", label: "Adamawa" },
  { value: "akwa ibom", label: "Akwa Ibom" },
  { value: "anambra", label: "Anambra" },
  { value: "bauchi", label: "Bauchi" },
  { value: "bayelsa", label: "Bayelsa" },
  { value: "benue", label: "Benue" },
  { value: "borno", label: "Borno" },
  { value: "cross river", label: "Cross River" },
  { value: "delta", label: "Delta" },
  { value: "ebonyi", label: "Ebonyi" },
  { value: "edo", label: "Edo" },
  { value: "ekiti", label: "Ekiti" },
  { value: "enugu", label: "Enugu" },
  { value: "gombe", label: "Gombe" },
  { value: "imo", label: "Imo" },
  { value: "jigawa", label: "Jigawa" },
  { value: "kaduna", label: "Kaduna" },
  { value: "kano", label: "Kano" },
  { value: "katsina", label: "Katsina" },
  { value: "kebbi", label: "Kebbi" },
  { value: "kogi", label: "Kogi" },
  { value: "kwara", label: "Kwara" },
  { value: "lagos", label: "Lagos" },
  { value: "nasarawa", label: "Nasarawa" },
  { value: "niger", label: "Niger" },
  { value: "ogun", label: "Ogun" },
  { value: "ondo", label: "Ondo" },
  { value: "osun", label: "Osun" },
  { value: "oyo", label: "Oyo" },
  { value: "plateau", label: "Plateau" },
  { value: "rivers", label: "Rivers" },
  { value: "sokoto", label: "Sokoto" },
  { value: "taraba", label: "Taraba" },
  { value: "yobe", label: "Yobe" },
  { value: "zamfara", label: "Zamfara" },
  { value: "fct", label: "FCT" }
];



export const validCities = [
  { value: "lagos", label: "Lagos" },
  { value: "abuja", label: "Abuja" },
  { value: "kano", label: "Kano" },
  { value: "ibadan", label: "Ibadan" },
  { value: "benin city", label: "Benin City" },
  { value: "port harcourt", label: "Port Harcourt" },
  { value: "enugu", label: "Enugu" },
  { value: "aba", label: "Aba" },
  { value: "jos", label: "Jos" },
  { value: "ilorin", label: "Ilorin" },
  { value: "maiduguri", label: "Maiduguri" },
  { value: "zaria", label: "Zaria" },
  { value: "abeokuta", label: "Abeokuta" },
  { value: "calabar", label: "Calabar" },
  { value: "ogbomosho", label: "Ogbomosho" },
  { value: "lokoja", label: "Lokoja" },
  { value: "uyo", label: "Uyo" },
  { value: "sokoto", label: "Sokoto" },
  { value: "kaduna", label: "Kaduna" },
  { value: "owerri", label: "Owerri" },
  { value: "warri", label: "Warri" },
  { value: "onitsha", label: "Onitsha" },
  { value: "bauchi", label: "Bauchi" },
  { value: "akure", label: "Akure" },
  { value: "gombe", label: "Gombe" },
  { value: "ikorodu", label: "Ikorodu" },
  { value: "ijebu ode", label: "Ijebu Ode" },
  { value: "katsina", label: "Katsina" },
  { value: "minna", label: "Minna" },
  { value: "makurdi", label: "Makurdi" },
  { value: "abakaliki", label: "Abakaliki" }
];



export const validCountries = [
  // Africa
  { value: "nigeria", label: "Nigeria" },
  { value: "ghana", label: "Ghana" },
  { value: "kenya", label: "Kenya" },
  { value: "south africa", label: "South Africa" },
  { value: "egypt", label: "Egypt" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "uganda", label: "Uganda" },
  { value: "tanzania", label: "Tanzania" },
  { value: "morocco", label: "Morocco" },
  { value: "algeria", label: "Algeria" },
  { value: "senegal", label: "Senegal" },
  { value: "cameroon", label: "Cameroon" },
  { value: "ivory coast", label: "Ivory Coast" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },
  { value: "rwanda", label: "Rwanda" },
  { value: "botswana", label: "Botswana" },
  { value: "sudan", label: "Sudan" },
  { value: "tunisia", label: "Tunisia" },
  { value: "mozambique", label: "Mozambique" },

  // Europe
  { value: "united kingdom", label: "United Kingdom" },
  { value: "france", label: "France" },
  { value: "germany", label: "Germany" },
  { value: "italy", label: "Italy" },
  { value: "spain", label: "Spain" },
  { value: "netherlands", label: "Netherlands" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },

  // Americas
  { value: "united states", label: "United States" },
  { value: "canada", label: "Canada" },
  { value: "brazil", label: "Brazil" },
  { value: "mexico", label: "Mexico" },
  { value: "argentina", label: "Argentina" },

  // Asia
  { value: "china", label: "China" },
  { value: "japan", label: "Japan" },
  { value: "india", label: "India" },
  { value: "south korea", label: "South Korea" },
  { value: "united arab emirates", label: "United Arab Emirates" },
  { value: "saudi arabia", label: "Saudi Arabia" },
  { value: "turkey", label: "Turkey" },

  // Oceania
  { value: "australia", label: "Australia" },
  { value: "new zealand", label: "New Zealand" }
];
